import * as fs from 'fs';
import * as path from 'path';
import { yarn } from 'cdklabs-projen-project-types';
import type { TypeScriptWorkspaceOptions } from 'cdklabs-projen-project-types/lib/yarn';
import type { IConstruct, IMixin } from 'constructs';
import { DependencyType, SourceCode } from 'projen';

const TOOLS_PACKAGE_NAME = '@aws-cdk/private-tools';

/** The single per-consumer re-export shim that all tool imports go through. */
const SHIM_TS = 'lib/private/tools.ts';
const SHIM_JS = 'lib/private/tools.js';

/**
 * Formal definition of a single tool's dependencies.
 */
export interface ToolDefinition {
  /** Runtime dependencies the tool imports (added to consumers). */
  readonly deps: string[];
  /** Dev dependencies needed to compile the tool source. */
  readonly devDeps?: string[];
}

export interface ToolsWorkspaceOptions extends Omit<TypeScriptWorkspaceOptions, 'name' | 'description' | 'srcdir'> {
  /**
   * Per-tool definitions, keyed by tool name.
   */
  readonly tools: Record<string, ToolDefinition>;
  /**
   * Additional dev dependencies for the tools package.
   */
  readonly devDeps?: string[];
}

/**
 * A typed handle to a single tool, usable as an IMixin via `.with(tools.zip)`.
 */
export class ToolMixin implements IMixin {
  constructor(
    /** The `@aws-cdk/private-tools` workspace that owns the tool. */
    public readonly workspace: ToolsWorkspace,
    /** The tool name (its directory under `lib/`). */
    public readonly name: string,
    /** The tool's declared definition. */
    public readonly definition: ToolDefinition,
  ) {
  }

  public supports(construct: IConstruct): construct is yarn.TypeScriptWorkspace {
    return construct instanceof yarn.TypeScriptWorkspace;
  }

  public applyTo(project: IConstruct): void {
    if (!this.supports(project)) {
      return;
    }

    // `@aws-cdk/private-tools` is a BUILD-time-only dependency: the consumer
    // compiles against it and inlines its code into the shim at pack time. It
    // is never a runtime dependency of the published package.
    if (!project.deps.tryGetDependency(TOOLS_PACKAGE_NAME)) {
      project.addWorkspaceDep(this.workspace, DependencyType.BUILD);
    }

    // The tool's third-party deps are kept EXTERNAL when the shim is bundled,
    // so they must be real runtime dependencies of the consumer (and dedupe to
    // a single shared copy when a bundler, e.g. the CLI, pulls everything in).
    for (const spec of this.definition.deps) {
      if (!project.deps.tryGetDependency(packageName(spec))) {
        project.addDeps(spec);
      }
    }

    // All consumer code imports the tool from the single generated re-export
    // shim (`./private/tools`); importing `@aws-cdk/private-tools` directly is
    // banned (see below), so the pack-time bundle has exactly one entry point.
    const shim = shimFor(project);
    shim.line(`export * from '${TOOLS_PACKAGE_NAME}/lib/${this.name}';`);
    shim.line(''); // trailing newline: the shim is read-only, so it must be lint-clean as generated
    banDirectImports(project, this.name);
    addPackTimeBundling(project);

    // The shim is a trivial generated re-export; keep it out of coverage.
    const jest = project.tryFindObjectFile('jest.config.json');
    jest?.addOverride(
      'coveragePathIgnorePatterns',
      [...new Set<string>([...((jest as any).obj?.coveragePathIgnorePatterns ?? []), `${SHIM_JS.replace('.', '\\.')}$`])],
    );
  }
}

/**
 * Get (creating on first use) the single re-export shim for a consumer.
 *
 * The shim carries the standard projen marker so it is recognised as a
 * generated file, plus eslint-disable directives because it is the one place
 * allowed to import the build-time-only `@aws-cdk/private-tools` package.
 */
const SHIMS = new WeakMap<IConstruct, SourceCode>();
function shimFor(project: yarn.TypeScriptWorkspace): SourceCode {
  let shim = SHIMS.get(project);
  if (!shim) {
    // Not read-only: the shim lives under `lib/`, which is an nx build-cache
    // output. A read-only file there breaks cache restore (and `eslint --fix`)
    // with EACCES. It is still regenerated by `npx projen`.
    shim = new SourceCode(project, SHIM_TS, { readonly: false });
    shim.line(`// ${shim.marker}`);
    shim.line('');
    shim.line('/* eslint-disable import/no-extraneous-dependencies -- re-exports the build-time-only @aws-cdk/private-tools package */');
    shim.line('/* eslint-disable no-restricted-imports -- this shim is the single sanctioned entry point to @aws-cdk/private-tools */');
    SHIMS.set(project, shim);
  }
  return shim;
}

/** Forbid importing `@aws-cdk/private-tools` anywhere except the shim. */
function banDirectImports(project: yarn.TypeScriptWorkspace, toolName: string): void {
  const eslint = (project as any).eslint;
  if (!eslint) {
    return;
  }
  // Merge into any existing `no-restricted-imports` rule (e.g. the shared
  // punycode restriction) instead of replacing it. We add our bans via `paths`
  // — which, unlike `patterns`, may contain a mix of strings and objects — so
  // the existing configuration is preserved untouched.
  const existing = eslint.rules?.['no-restricted-imports'];
  const options = Array.isArray(existing) && typeof existing[1] === 'object' ? { ...existing[1] } : {};
  const paths = [...(options.paths ?? [])];
  const message = `Import shared tools from './private/tools' (the generated shim), not '${TOOLS_PACKAGE_NAME}' directly.`;
  for (const name of [TOOLS_PACKAGE_NAME, `${TOOLS_PACKAGE_NAME}/lib/${toolName}`]) {
    if (!paths.some((p: any) => (typeof p === 'string' ? p : p.name) === name)) {
      paths.push({ name, message });
    }
  }
  eslint.addRules({ 'no-restricted-imports': ['error', { ...options, paths }] });
}

/**
 * Bundle ONLY our code into the shim at pack time.
 *
 * `esbuild` inlines the build-time-only `@aws-cdk/private-tools` source while
 * every declared runtime dependency stays external (so the published package
 * still depends on e.g. `archiver`/`fast-glob` and they dedupe normally). The
 * workspace copy of the shim is restored to its plain re-export afterwards, so
 * in-repo bundling (the CLI) keeps deduping transitive deps to a single copy.
 */
const BUNDLED = new WeakSet<IConstruct>();
function addPackTimeBundling(project: yarn.TypeScriptWorkspace): void {
  if (BUNDLED.has(project)) {
    return;
  }
  BUNDLED.add(project);

  if (!project.deps.tryGetDependency('esbuild')) {
    project.addDevDeps('esbuild');
  }

  const bundle = [
    'const esbuild=require(\'esbuild\');',
    'const pkg=require(\'./package.json\');',
    `esbuild.buildSync({entryPoints:['${SHIM_JS}'],bundle:true,platform:'node',target:'node18',external:Object.keys(pkg.dependencies||{}),allowOverwrite:true,outfile:'${SHIM_JS}'});`,
  ].join('');
  project.packageTask.prependExec(`cp ${SHIM_JS} ${SHIM_JS}.plain && node -e "${bundle}"`);
  project.packageTask.exec(`mv ${SHIM_JS}.plain ${SHIM_JS}`);
}

/**
 * Private monorepo package that hosts small, self-contained utilities.
 *
 * Each subdirectory of `lib/` is a "tool" with its own `index.ts` source.
 * Tools are auto-discovered from the filesystem.
 */
export class ToolsWorkspace extends yarn.TypeScriptWorkspace {
  public readonly toolNames: readonly string[];
  public readonly tools: Record<string, ToolDefinition>;

  constructor(options: ToolsWorkspaceOptions) {
    const allDeps = [...new Set(Object.values(options.tools).flatMap((t) => t.deps))];
    const allDevDeps = [
      ...(options.devDeps ?? []),
      ...new Set(Object.values(options.tools).flatMap((t) => t.devDeps ?? [])),
    ];

    super({
      ...options,
      name: TOOLS_PACKAGE_NAME,
      description: 'Bundled utility tools that other packages cherry-pick from',
      srcdir: 'lib',
      private: true,
      devDeps: allDevDeps,
    });

    this.tools = options.tools;
    this.addDeps(...allDeps);

    this.toolNames = discoverTools(path.join(options.parent?.outdir ?? '.', 'packages/@aws-cdk/private-tools/lib'));

    for (const tool of this.toolNames) {
      if (!(tool in this.tools)) {
        throw new Error(`Tool '${tool}' does not declare its definition in 'tools' (use { deps: [] } if it has none)`);
      }
    }

    this.gitignore.addPatterns('*.js', '*.d.ts');
  }

  public toolMixin(name: string): ToolMixin {
    if (!(name in this.tools)) {
      throw new Error(`Unknown tool '${name}'; declared tools: ${Object.keys(this.tools).join(', ')}`);
    }
    return new ToolMixin(this, name, this.tools[name]);
  }
}

/**
 * Construct a {@link ToolsWorkspace} and expose a typed {@link ToolMixin} for
 * each declared tool as a property on the returned object.
 *
 * @example
 * const tools = defineTools({ parent: repo, tools: { zip: { deps: ['archiver'] } } });
 * someProject.with(tools.zip);
 */
export function defineTools<T extends Record<string, ToolDefinition>>(
  options: Omit<ToolsWorkspaceOptions, 'tools'> & { readonly tools: T },
): ToolsWorkspace & { readonly [K in keyof T]: ToolMixin } {
  const workspace = new ToolsWorkspace(options);
  const withRefs = workspace as ToolsWorkspace & Record<string, ToolMixin>;
  for (const name of Object.keys(options.tools)) {
    if (name in workspace) {
      throw new Error(`Tool name '${name}' collides with an existing ToolsWorkspace member; rename the tool`);
    }
    withRefs[name] = workspace.toolMixin(name);
  }
  return withRefs as ToolsWorkspace & { readonly [K in keyof T]: ToolMixin };
}

function discoverTools(dir: string): string[] {
  if (!fs.existsSync(dir)) {
    return [];
  }
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory() && fs.existsSync(path.join(dir, e.name, 'index.ts')))
    .map((e) => e.name)
    .sort();
}

function packageName(spec: string): string {
  const start = spec.startsWith('@') ? 1 : 0;
  const at = spec.indexOf('@', start);
  return at === -1 ? spec : spec.slice(0, at);
}
